---
- name: Apt Update servers
  hosts: all
  become: yes
  become_method: sudo

  tasks:
    # Update cache
    - name: update apt list
      apt:
        update_cache: yes

    # Upgrade packages
    - name: upgrade apt packages
      apt:
        upgrade: yes

    # Check if reboot is required
    - name: check if system reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required
