---
- name: Apt Update servers
  hosts: all
  become: yes
  become_method: sudo
  become_user: root
  tasks:
    - name: Update and upgrade the system
      apt:
        update_cache: yes
        upgrade: dist
        cache_valid_time: 3600

    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
    - name: Add Docker repository
      apt_repository:
        repo: deb [docker.com/repo]
      state: present
    - name: Add Docker's official GPG key
      ansible.builtin.command:
        cmd: sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
      args:
        creates: /usr/share/keyrings/docker-archive-keyring.gpg

    - name: Add Docker repository
      ansible.builtin.command:
        cmd: echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
      args:
        creates: /etc/apt/sources.list.d/docker.list

    - name: Update package index
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name:
          - docker
          - containerd.io
        state: present

    - name: Add user to Docker group
      user:
        name: "{{ ansible_user_id }}"
        groups: docker
        append: yes

    - name: Install Docker Compose
      ansible.builtin.command:
        cmd: curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      args:
        creates: /usr/local/bin/docker-compose

    - name: Apply executable permissions to Docker Compose binary
      file:
        path: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Verify Docker installation
      command: docker --version
      register: docker_version_output

    - name: Debug Docker version
      debug:
        msg: "{{ docker_version_output.stdout }}"

    - name: Verify Docker Compose installation
      command: docker-compose --version
      register: docker_compose_version_output

    - name: Debug Docker Compose version
      debug:
        msg: "{{ docker_compose_version_output.stdout }}"
