---
- name: Apt Update servers
  hosts: all
  become: yes
  become_method: sudo
  become_user: root
  tasks:
  tasks:
    - name: Update and upgrade the system
      apt:
        update_cache: yes
        upgrade: dist
        cache_valid_time: 3600

    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: present

    - name: Add Docker's GPG key using get_url
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'
    - name: Add Docker repository
      shell:
        'echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \$(. /etc/os-release && echo "$VERSION_CODENAME") stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null'

    - name: Update package index
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Add user to Docker group
      user:
        name: "{{ ansible_user_id }}"
        groups: docker
        append: yes

    - name: Install Docker Compose
      ansible.builtin.command:
        cmd: curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      args:
        creates: /usr/local/bin/docker-compose

    - name: Apply executable permissions to Docker Compose binary
      file:
        path: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Verify Docker installation
      command: docker --version
      register: docker_version_output

    - name: Debug Docker version
      debug:
        msg: "{{ docker_version_output.stdout }}"

    - name: Verify Docker Compose installation
      command: docker-compose --version
      register: docker_compose_version_output

    - name: Debug Docker Compose version
      debug:
        msg: "{{ docker_compose_version_output.stdout }}"
